apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-consumer
  namespace: portfolio
  labels:
    app.kubernetes.io/name: blog
    app.kubernetes.io/component: consumer
    app.kubernetes.io/part-of: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blog
      app.kubernetes.io/component: consumer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blog
        app.kubernetes.io/component: consumer
    spec:
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: consumer
          image: ghcr.io/szymonborowski/microservices-blog:v0.0.1
          imagePullPolicy: Never
          args: ["php", "artisan", "rabbitmq:consume-users"]
          envFrom:
            - configMapRef:
                name: blog-config
            - secretRef:
                name: blog-secret
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 256Mi
